### ISSUE TITLE
Figure out better names

### ISSUE THREAD

**Issue by mvdan** [mvdan/lint#1]
Should `Checker` be `Linter`?

Should `Warning` be `Issue`?

Just some ideas. Names aren't set in stone.

**Comment by bradleyfalzon** [comment]
IMHO I like `Checker` and `Issue` (or `Messsage` instead of `Issue`, but I like `Issue` more). Although, my thoughts are mostly bike shedding.

**Comment by mvdan** [comment]
I like `Checker` a bit more than `Linter` as the latter stutters - `lint.Linter`.

I don't have strong feelings on `Warning` vs `Issue`. Definitely not `Error` though.

**Comment by thomasheller** [comment]
I guess it should be `Issue` (more generic) instead of `Warning`. If you decide that linters can categorize their warnings (per #2) later on, things might get a little confusing if a linter categorizes its results by severity "warning", "error" and so on. Then there would be "warnings" of type "warning" and "error". In that case, I'd rather have "issues" of type "warning" and "error".

**Comment by mvdan** [comment]
Done - thanks for the suggestions.

I'll keep this issue open for other naming discussions.

**Comment by mvdan** [comment]
Actually, this doesn't matter much because type aliases will be a thing soon enough.
